# This is the default dev tool configuration for Wish projects living in
# clroot.
#
# More information about the dev tool can be found on its project page at
# https://github.com/wish/dev or you can reach out on #container-eng
#
# If you would like to be able to control your containers outside of $CL_HOME,
# you can set the DEV_CONFIG environment variable to the path of this file,
# i.e., export DEV_CONFIG=$CL_HOME/.dev.yaml

log:
  level: "info"

projects:
  submit_code:
    docker_compose_files:
      - "./submit-code-compose.yml"